### ISSUE TITLE
Add pre-commit and exercise on CI

### ISSUE THREAD

**Issue by raulcd** [apache/iceberg-cpp#15]
We have already added Clang and CMake format in:
- https://github.com/apache/iceberg-cpp/pull/4
- https://github.com/apache/iceberg-cpp/pull/5

We should add pre-commit to perform the linter on CI.

We can also add yaml format as discussed here:
https://github.com/apache/iceberg-cpp/pull/10#issuecomment-2547863756

**Comment by Fokko** [comment]
This was also suggested by @pitrou in https://github.com/apache/iceberg-cpp/pull/5#issuecomment-2541796460

**Comment by zhjwpku** [comment]
I think this issue can be closed as we have already done that ;)

**Comment by raulcd** [comment]
Yes, it was supposed to be closed with:
https://github.com/apache/iceberg-cpp/pull/16
Thanks @zhjwpku
